#!/usr/bin/python3

import click

from commands.run import exec_run
from commands.images import exec_images
from commands.pull import exec_pull


@click.group()
def cli():
    pass


@click.command()
def images():
    exec_images()


@click.command()
@click.argument('image_name',nargs=1)
def pull(image_name):
    exec_pull(image_name)


@click.command(context_settings={'ignore_unknown_options': True})
@click.argument('command',nargs=-1)
@click.option('--cpu',default=None,type=float)
def run(cpu,command):
    
    #Listは空ならfalseを返す。
    if not command:
        print("command need")
        return

    exec_run(cpu,command)
    


cli.add_command(images)
cli.add_command(pull)
cli.add_command(run)


if __name__ == '__main__':
    cli()
